services:
  backend:
    image: ghcr.io/ssciwr/predicTCR_backend:${PREDICTCR_DOCKER_IMAGE_TAG:-latest}
    build: ./backend
    volumes:
      - ${PREDICTCR_DATA:-./docker_volume}:/predicTCR_data
    environment:
      - JWT_SECRET_KEY=${PREDICTCR_JWT_SECRET_KEY:-}
  frontend:
    image: ghcr.io/ssciwr/predicTCR_frontend:${PREDICTCR_DOCKER_IMAGE_TAG:-latest}
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PREDICTCR_SSL_CERT:-./cert.pem}:/predicTCR_ssl_cert.pem
      - ${PREDICTCR_SSL_KEY:-./key.pem}:/predicTCR_ssl_key.pem
  email:
    image: "boky/postfix"
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS="true"
