services:
  backend:
    image: ghcr.io/ssciwr/predictcr_backend:${PREDICTCR_DOCKER_IMAGE_TAG:-latest}
    build: ./backend
    volumes:
      - ${PREDICTCR_DATA:-./docker_volume}:/predictcr_data
    environment:
      - JWT_SECRET_KEY=${PREDICTCR_JWT_SECRET_KEY:-}
    networks:
      - predictcr-network
  frontend:
    image: ghcr.io/ssciwr/predictcr_frontend:${PREDICTCR_DOCKER_IMAGE_TAG:-latest}
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PREDICTCR_SSL_CERT:-./cert.pem}:/predictcr_ssl_cert.pem
      - ${PREDICTCR_SSL_KEY:-./key.pem}:/predictcr_ssl_key.pem
      - ${PREDICTCR_CERTBOT_WWW:-/var/www/certbot}:/var/www/certbot:ro
    networks:
      - predictcr-network
  email:
    image: "boky/postfix"
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS="true"
    networks:
      - predictcr-network

networks:
  predictcr-network:
    name: predictcr
