services:
  runner:
    image: ghcr.io/ssciwr/predictcr_runner:${PREDICTCR_DOCKER_IMAGE_TAG:-latest}
    build: .
    environment:
      - PREDICTCR_API_URL=${PREDICTCR_API_URL:-https://predictcr.lkeegan.dev/api}
      - PREDICTCR_JWT_TOKEN=${PREDICTCR_JWT_TOKEN:-}
      - PREDICTCR_POLL_INTERVAL=${PREDICTCR_POLL_INTERVAL:-5}
      - PREDICTCR_LOG_LEVEL=${PREDICTCR_LOG_LEVEL:-INFO}
    deploy:
      mode: replicated
      replicas: ${PREDICTCR_RUNNER_JOBS:-1}
    restart: always
    networks:
      - predictcr-network

networks:
  predictcr-network:
    name: predictcr
