services:
  runner:
    image: ghcr.io/ssciwr/predictcr_runner:${PREDICTCR_DOCKER_IMAGE_TAG:-latest}
    build: .
    volumes:
      - ${PREDICTCR_RUNNER_DATA_DIR:-./data}:/data
    environment:
      - PREDICTCR_API_URL=${PREDICTCR_API_URL:-https://predictcr.iwr.uni-heidelberg.de/api}
      - PREDICTCR_JWT_TOKEN=${PREDICTCR_JWT_TOKEN:-}
      - PREDICTCR_POLL_INTERVAL=${PREDICTCR_POLL_INTERVAL:-5}
      - PREDICTCR_LOG_LEVEL=${PREDICTCR_LOG_LEVEL:-INFO}
    deploy:
      mode: replicated
      replicas: ${PREDICTCR_RUNNERS:-1}
    networks:
      - predictcr-network

networks:
  predictcr-network:
    name: predictcr
